"""
FastAPI application entry point.
Auto-generated by NIKAME for project: my-app----[b-[b
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from config import settings
import time
import logging

from core.cache import cache
from routers import health
from sqlalchemy import text
from app.routers.health import router

# Setup logging
class JSONFormatter(logging.Formatter):
    def format(self, record):
        log_data = {
            "timestamp": self.formatTime(record),
            "level": record.levelname,
            "message": record.getMessage(),
            "module": record.module,
            "service": settings.APP_NAME,
        }
        if record.exc_info:
            log_data["exception"] = self.formatException(record.exc_info)
        return json.dumps(log_data)

handler = logging.StreamHandler()
handler.setFormatter(JSONFormatter())
logging.basicConfig(level=logging.INFO, handlers=[handler])
logger = logging.getLogger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup logic
    logger.info(f"🚀 Starting {settings.APP_NAME} [{settings.APP_ENV}]")
    
    # 1. Database connection check
    if False:
        try:
            async with db_engine.connect() as conn:
                await conn.execute(text("SELECT 1"))
            logger.info("✓ Database connection verified")
        except Exception as e:
            logger.error(f"✗ Database connection failed: {e}")
    
    # 2. Redis/Dragonfly connection check
    if True:
        try:
            await cache.connect()
            logger.info("✓ Cache connection verified")
        except Exception as e:
            logger.error(f"✗ Cache connection failed: {e}")

    # 3. Kafka/RedPanda connection check
    if False:
        try:
            await kafka_service.start()
            logger.info("✓ Messaging service (Kafka) started")
        except Exception as e:
            logger.error(f"✗ Messaging service failed: {e}")

    if False:
        from core.features import start_features
        start_features()

    if False:
        init_tracking()
        logger.info("✓ MLflow tracking initialized")

    if False:
        init_observability(app)
        logger.info("✓ ML Observability initialized")

    if False:
        try:
            await init_limiter(app)
            logger.info("✓ Rate limiter initialized")
        except Exception as e:
            logger.error(f"✗ Rate limiter failed: {e}")

    yield
    
    # Shutdown logic
    if False:
        await db_engine.dispose()
    if True:
        await cache.disconnect()
    if False:
        await kafka_service.stop()
        
    logger.info(f"💤 Shutting down {settings.APP_NAME}")

app = FastAPI(
    title=settings.APP_NAME,
    description="Full-stack API generated by NIKAME",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

# Middleware for request timing
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response

# CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Exception Handler
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Global error: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal Server Error", "type": type(exc).__name__},
    )

# Routes
app.include_router(health.router)

@app.get("/", tags=["root"])
async def root():
    return {
        "message": f"Welcome to {settings.APP_NAME}",
        "env": settings.APP_ENV,
        "docs": "/docs",
        "health": "/health"
    }
app.include_router(router)
