apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: local
spec:
  serviceName: redpanda
  replicas: {{ .Values.global.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: redpandadata/redpanda:latest
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 8081
          name: schema-registry
        - containerPort: 9644
          name: admin
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
