apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: project-secrets
  namespace: local
  annotations:
    sealedsecrets.bitnami.com/managed: 'true'
spec:
  encryptedData:
    KEYCLOAK_URL: Ag...base64_placeholder...
  template:
    metadata:
      name: project-secrets
      labels:
        nikame.role: secrets
