"""
Application Factory.

Provides a `create_app()` function to dynamically build the FastAPI
application instance based on environment settings.
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from {{APP_NAME}}.core.settings import settings
from {{APP_NAME}}.core.lifespan import app_lifespan


def create_app() -> FastAPI:
    """Create and configure the FastAPI application instance."""
    app = FastAPI(
        title="{{APP_NAME}}",
        description="Application generated by fastcheat",
        version="0.1.0",
        debug=settings.DEBUG,
        lifespan=app_lifespan,
        docs_url="/docs" if settings.APP_ENV != "production" else None,
        redoc_url="/redoc" if settings.APP_ENV != "production" else None,
        openapi_url="/openapi.json" if settings.APP_ENV != "production" else None,
    )

    # Note: Error handlers should be registered here if you ran:
    # fastcheat add core/error-handlers
    # from {{APP_NAME}}.core.handlers import register_error_handlers
    # register_error_handlers(app)

    # Default CORS setup
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"] if settings.DEBUG else ["https://yourproductiondomain.com"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Register root router or generic handlers
    @app.get("/", tags=["health"])
    async def root() -> dict[str, str]:
        return {"status": "ok", "env": settings.APP_ENV}

    return app


# The main application instance to be run by uvicorn
app = create_app()
